# Generated by Django 4.2.6 on 2024-04-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0005_ticket_remove_orderitem_item_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='items/default.jpg', upload_to='items/'),
        ),
    ]
