# Generated by Django 4.2.6 on 2024-04-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0006_cart_progress_item_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='stock',
        ),
    ]
